version: "3.8"

services:

  db:
    image: 172.16.29.3:5000/timescaledb:latest-pg12
    # command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    command: ["postgres"]
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      # - "./my-postgres.conf:/etc/postgresql.conf"

    networks:
      - internal_net

  nmea_ingest:
    build: ./nmea_ingest
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASS: password
    ports:  
      - "1234:1234/udp"
    volumes:
      - "./nmea_ingest/ingest.py:/ingest.py"
      - "./nmea_ingest/tester.py:/tester.py"
    networks:
      - internal_net
      - external_net



  postgrest:
    image: 172.16.29.3:5000/postgrest
    restart: always
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: elog
      PGRST_DB_ANON_ROLE: nuyinapi_ro
      PGRST_SERVER_PORT: 4444
      PGRST_MAX_ROWS: 1000
      PGRST_JWT_SECRET: "HwifBC4JehYun4FMJ17ctLjtEHpCmrzR"
    ports:
      - "3001:4444"
    networks:
      - internal_net
      - external_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - external_net
      - internal_net


volumes:
  pgadmin-data:

networks:
  internal_net:
    internal: true
  external_net:
